name: Send LINE Menu Bot

on:
  schedule:
    # 日本時間(JST)の毎朝7時に実行するため、UTCで前日の22時に設定
    - cron: '0 22, 3, 9 * * *'
  # 手動でも実行できるようにするおまじない
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. 必要なライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Pythonスクリプトを実行
      - name: Run Python Script
        env:
          # 手順2で設定したGitHub Secretsを環境変数としてスクリプトに渡す
          CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python main2.py
